version: "3.7"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: piyush-homelab-fileflows_server_1
      APP_PORT: 5111

  server:
    image: revenz/fileflows
    init: true
    environment:
      - TZ=America/Toronto
      - TempPathHost=/temp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APP_DATA_DIR}/data:/app/Data
      - ${APP_DATA_DIR}/data/logs:/app/Logs
      - ${APP_DATA_DIR}/data/temp:/temp
      - /media/media-for-home:/media
    restart: unless-stopped
