version: "3.7"
services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: piyush-homelab-gluetun_server_1
      APP_PORT: 8888

  server:
    image: qmcgaw/gluetun:v3@sha256:e15ede3ce007e3f6e3f6532c7d8d6051f4bb0dca4bb3c5edd7aa3316916e9990
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8111:8000/tcp # Built-in HTTP control server
      - 6081:6881
      - 6081:6881/udp
      - 6011:6011
    # command:
    volumes:
      - ${APP_DATA_DIR}/data/gluetun:/gluetun
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # More variables are available, see the Wiki table
      - VPNSP=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${MULLVAD_USER}
    restart: always
