version: "3.7"
services:
  app_proxy:
  environment:
    # The format here is: <app-id>_<docker-service-name>_1
    APP_HOST: fileflows_fileflows_1
    APP_PORT: 5000

  fileflows:
    image: revenz/fileflows
    init: true
    container_name: fileflows
    environment:
      - TZ=America/Toronto
      - TempPathHost=/temp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /path/to/data:/app/Data
      - /path/to/logs:/app/Logs
      - /path/to/temp:/temp
      - /media/media-for-home:/media
    ports:
      - 5000:5000
    restart: unless-stopped
